//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSLEditor.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SecondLife Name")]
        public string AvatarName {
            get {
                return ((string)(this["AvatarName"]));
            }
            set {
                this["AvatarName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BrowserInWindow {
            get {
                return ((bool)(this["BrowserInWindow"]));
            }
            set {
                this["BrowserInWindow"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000-0000-0000-0000-000000000000")]
        public string AvatarKey {
            get {
                return ((string)(this["AvatarKey"]));
            }
            set {
                this["AvatarKey"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LSLEditor Island")]
        public string RegionName {
            get {
                return ((string)(this["RegionName"]));
            }
            set {
                this["RegionName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.emailserver.ext")]
        public string EmailServer {
            get {
                return ((string)(this["EmailServer"]));
            }
            set {
                this["EmailServer"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("youraddress@yourdomain.ext")]
        public string EmailAddress {
            get {
                return ((string)(this["EmailAddress"]));
            }
            set {
                this["EmailAddress"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProxyServer {
            get {
                return ((string)(this["ProxyServer"]));
            }
            set {
                this["ProxyServer"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProxyUserid {
            get {
                return ((string)(this["ProxyUserid"]));
            }
            set {
                this["ProxyUserid"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProxyPassword {
            get {
                return ((string)(this["ProxyPassword"]));
            }
            set {
                this["ProxyPassword"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point BrowserLocation {
            get {
                return ((global::System.Drawing.Point)(this["BrowserLocation"]));
            }
            set {
                this["BrowserLocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FindLocation {
            get {
                return ((global::System.Drawing.Point)(this["FindLocation"]));
            }
            set {
                this["FindLocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size BrowserSize {
            get {
                return ((global::System.Drawing.Size)(this["BrowserSize"]));
            }
            set {
                this["BrowserSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.lslwiki.net/lslwiki/wakka.php?wakka=")]
        public string Help {
            get {
                return ((string)(this["Help"]));
            }
            set {
                this["Help"] = value;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resource.ConfLSL.xml")]
        public string ConfLSL {
            get {
                return ((string)(this["ConfLSL"]));
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LSLEditorLocation {
            get {
                return ((global::System.Drawing.Point)(this["LSLEditorLocation"]));
            }
            set {
                this["LSLEditorLocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size LSLEditorSize {
            get {
                return ((global::System.Drawing.Size)(this["LSLEditorSize"]));
            }
            set {
                this["LSLEditorSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public double RegionFPS {
            get {
                return ((double)(this["RegionFPS"]));
            }
            set {
                this["RegionFPS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 175")]
        public global::System.Drawing.Size SimulatorSize {
            get {
                return ((global::System.Drawing.Size)(this["SimulatorSize"]));
            }
            set {
                this["SimulatorSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point SimulatorLocation {
            get {
                return ((global::System.Drawing.Point)(this["SimulatorLocation"]));
            }
            set {
                this["SimulatorLocation"] = value;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("New Script.lsl")]
        public string ExampleName {
            get {
                return ((string)(this["ExampleName"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("New Script.lsli")]
        public string ExampleNameLSLI {
            get {
                return ((string)(this["ExampleNameLSLI"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ReleaseNotes.htm")]
        public string ReleaseNotes {
            get {
                return ((string)(this["ReleaseNotes"]));
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("254464, 255232")]
        public global::System.Drawing.Point RegionCorner {
            get {
                return ((global::System.Drawing.Point)(this["RegionCorner"]));
            }
            set {
                this["RegionCorner"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TabbedDocument {
            get {
                return ((bool)(this["TabbedDocument"]));
            }
            set {
                this["TabbedDocument"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SLColorScheme {
            get {
                return ((bool)(this["SLColorScheme"]));
            }
            set {
                this["SLColorScheme"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SL4SpacesIndent {
            get {
                return ((bool)(this["SL4SpacesIndent"]));
            }
            set {
                this["SL4SpacesIndent"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoWordSelection {
            get {
                return ((bool)(this["AutoWordSelection"]));
            }
            set {
                this["AutoWordSelection"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point GotoLocation {
            get {
                return ((global::System.Drawing.Point)(this["GotoLocation"]));
            }
            set {
                this["GotoLocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WikiSeperateBrowser {
            get {
                return ((bool)(this["WikiSeperateBrowser"]));
            }
            set {
                this["WikiSeperateBrowser"] = value;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("About.htm")]
        public string About {
            get {
                return ((string)(this["About"]));
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("224, 224, 224")]
        public global::System.Drawing.Color BracketHighlight {
            get {
                return ((global::System.Drawing.Color)(this["BracketHighlight"]));
            }
            set {
                this["BracketHighlight"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("175, 0")]
        public global::System.Drawing.Size SolutionSize {
            get {
                return ((global::System.Drawing.Size)(this["SolutionSize"]));
            }
            set {
                this["SolutionSize"] = value;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int TabStops {
            get {
                return ((int)(this["TabStops"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ToolTipDelay {
            get {
                return ((int)(this["ToolTipDelay"]));
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CallUpgrade {
            get {
                return ((bool)(this["CallUpgrade"]));
            }
            set {
                this["CallUpgrade"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int RecentFileMax {
            get {
                return ((int)(this["RecentFileMax"]));
            }
            set {
                this["RecentFileMax"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckForUpdates {
            get {
                return ((bool)(this["CheckForUpdates"]));
            }
            set {
                this["CheckForUpdates"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckEveryDay {
            get {
                return ((bool)(this["CheckEveryDay"]));
            }
            set {
                this["CheckEveryDay"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckEveryWeek {
            get {
                return ((bool)(this["CheckEveryWeek"]));
            }
            set {
                this["CheckEveryWeek"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2010-01-01")]
        public global::System.DateTime CheckDate {
            get {
                return ((global::System.DateTime)(this["CheckDate"]));
            }
            set {
                this["CheckDate"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentProjectList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentProjectList"]));
            }
            set {
                this["RecentProjectList"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int RecentProjectMax {
            get {
                return ((int)(this["RecentProjectMax"]));
            }
            set {
                this["RecentProjectMax"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentFileList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentFileList"]));
            }
            set {
                this["RecentFileList"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IndentCursorPlacement {
            get {
                return ((bool)(this["IndentCursorPlacement"]));
            }
            set {
                this["IndentCursorPlacement"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IndentFullAuto {
            get {
                return ((bool)(this["IndentFullAuto"]));
            }
            set {
                this["IndentFullAuto"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Indent {
            get {
                return ((bool)(this["Indent"]));
            }
            set {
                this["Indent"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font FontEditor {
            get {
                return ((global::System.Drawing.Font)(this["FontEditor"]));
            }
            set {
                this["FontEditor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font FontTooltips {
            get {
                return ((global::System.Drawing.Font)(this["FontTooltips"]));
            }
            set {
                this["FontTooltips"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Bugreports {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Bugreports"]));
            }
            set {
                this["Bugreports"] = value;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int PathClipLength {
            get {
                return ((int)(this["PathClipLength"]));
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SmtpUserid {
            get {
                return ((string)(this["SmtpUserid"]));
            }
            set {
                this["SmtpUserid"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SmtpPassword {
            get {
                return ((string)(this["SmtpPassword"]));
            }
            set {
                this["SmtpPassword"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PLAIN")]
        public string SmtpAuth {
            get {
                return ((string)(this["SmtpAuth"]));
            }
            set {
                this["SmtpAuth"] = value;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default.lsl")]
        public string ExampleTemplate {
            get {
                return ((string)(this["ExampleTemplate"]));
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HelpOnline {
            get {
                return ((bool)(this["HelpOnline"]));
            }
            set {
                this["HelpOnline"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HelpOffline {
            get {
                return ((bool)(this["HelpOffline"]));
            }
            set {
                this["HelpOffline"] = value;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LSLEditorHelp.chm")]
        public string HelpOfflineFile {
            get {
                return ((string)(this["HelpOfflineFile"]));
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CVSEXE {
            get {
                return ((string)(this["CVSEXE"]));
            }
            set {
                this["CVSEXE"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CVSROOT {
            get {
                return ((string)(this["CVSROOT"]));
            }
            set {
                this["CVSROOT"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProjectLocation {
            get {
                return ((string)(this["ProjectLocation"]));
            }
            set {
                this["ProjectLocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection IncludeDirectories {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["IncludeDirectories"]));
            }
            set {
                this["IncludeDirectories"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowIncludeMetaData {
            get {
                return ((bool)(this["ShowIncludeMetaData"]));
            }
            set {
                this["ShowIncludeMetaData"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeleteOldFiles {
            get {
                return ((bool)(this["DeleteOldFiles"]));
            }
            set {
                this["DeleteOldFiles"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CodeCompletionUserVar {
            get {
                return ((bool)(this["CodeCompletionUserVar"]));
            }
            set {
                this["CodeCompletionUserVar"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeCompletion {
            get {
                return ((bool)(this["CodeCompletion"]));
            }
            set {
                this["CodeCompletion"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CommentCStyle {
            get {
                return ((bool)(this["CommentCStyle"]));
            }
            set {
                this["CommentCStyle"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SkipWarnings {
            get {
                return ((bool)(this["SkipWarnings"]));
            }
            set {
                this["SkipWarnings"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SingleQuote {
            get {
                return ((bool)(this["SingleQuote"]));
            }
            set {
                this["SingleQuote"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QuotesListVerbose {
            get {
                return ((bool)(this["QuotesListVerbose"]));
            }
            set {
                this["QuotesListVerbose"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Plugins {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Plugins"]));
            }
            set {
                this["Plugins"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeCompletionArguments {
            get {
                return ((bool)(this["CodeCompletionArguments"]));
            }
            set {
                this["CodeCompletionArguments"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IndentWarning {
            get {
                return ((bool)(this["IndentWarning"]));
            }
            set {
                this["IndentWarning"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IndentAutoCorrect {
            get {
                return ((bool)(this["IndentAutoCorrect"]));
            }
            set {
                this["IndentAutoCorrect"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SvnExe {
            get {
                return ((string)(this["SvnExe"]));
            }
            set {
                this["SvnExe"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SvnUserid {
            get {
                return ((string)(this["SvnUserid"]));
            }
            set {
                this["SvnUserid"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SvnPassword {
            get {
                return ((string)(this["SvnPassword"]));
            }
            set {
                this["SvnPassword"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowSolutionExplorer {
            get {
                return ((bool)(this["ShowSolutionExplorer"]));
            }
            set {
                this["ShowSolutionExplorer"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WorkingDirectory {
            get {
                return ((string)(this["WorkingDirectory"]));
            }
            set {
                this["WorkingDirectory"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Production")]
        public string XSecondLifeShard {
            get {
                return ((string)(this["XSecondLifeShard"]));
            }
            set {
                this["XSecondLifeShard"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoSaveOnDebug {
            get {
                return ((bool)(this["AutoSaveOnDebug"]));
            }
            set {
                this["AutoSaveOnDebug"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToolTip {
            get {
                return ((bool)(this["ToolTip"]));
            }
            set {
                this["ToolTip"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HelpNewTab {
            get {
                return ((bool)(this["HelpNewTab"]));
            }
            set {
                this["HelpNewTab"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeCompletionAnimation {
            get {
                return ((bool)(this["CodeCompletionAnimation"]));
            }
            set {
                this["CodeCompletionAnimation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("New Note.txt")]
        public string ExampleNameNotecard {
            get {
                return ((string)(this["ExampleNameNotecard"]));
            }
            set {
                this["ExampleNameNotecard"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool llGetScriptName {
            get {
                return ((bool)(this["llGetScriptName"]));
            }
            set {
                this["llGetScriptName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StatesInGlobalFunctions {
            get {
                return ((bool)(this["StatesInGlobalFunctions"]));
            }
            set {
                this["StatesInGlobalFunctions"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LSLEditor parcel")]
        public string ParcelName {
            get {
                return ((string)(this["ParcelName"]));
            }
            set {
                this["ParcelName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Description of LSLEditor parcel")]
        public string ParcelDescription {
            get {
                return ((string)(this["ParcelDescription"]));
            }
            set {
                this["ParcelDescription"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000-0000-0000-0000-000000000000")]
        public string ParcelOwner {
            get {
                return ((string)(this["ParcelOwner"]));
            }
            set {
                this["ParcelOwner"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000-0000-0000-0000-000000000000")]
        public string ParcelGroup {
            get {
                return ((string)(this["ParcelGroup"]));
            }
            set {
                this["ParcelGroup"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public int ParcelArea {
            get {
                return ((int)(this["ParcelArea"]));
            }
            set {
                this["ParcelArea"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000-0000-0000-0000-000000000000")]
        public string ParcelID {
            get {
                return ((string)(this["ParcelID"]));
            }
            set {
                this["ParcelID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ParcelSeeAvatars {
            get {
                return ((int)(this["ParcelSeeAvatars"]));
            }
            set {
                this["ParcelSeeAvatars"] = value;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          default
          {
          state_entry()
          {
          llSay(0, ""Hello, Avatar!"");
          }

          touch_start(integer total_number)
          {
          llSay(0, ""Touched: "" + (string)total_number);
          }
          }
        ")]
        public string Example {
            get {
                return ((string)(this["Example"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.lsleditor.org/examples/")]
        public string Examples {
            get {
                return ((string)(this["Examples"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.lsleditor.org/uploadscript/")]
        public string Upload {
            get {
                return ((string)(this["Upload"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resource.ConfCSharp.xml")]
        public string ConfCSharp {
            get {
                return ((string)(this["ConfCSharp"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resource.ToolsOptions.xml")]
        public string ToolsOptions {
            get {
                return ((string)(this["ToolsOptions"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sourceforge.net/tracker/?group_id=319248")]
        public string ContactUrl {
            get {
                return ((string)(this["ContactUrl"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.lsleditor.org/donate.htm")]
        public string DonateUrl {
            get {
                return ((string)(this["DonateUrl"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://wiki.secondlife.com/wiki/Special:Search?go=Go&search=")]
        public string Help2 {
            get {
                return ((string)(this["Help2"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.lslwiki.net/lslwiki/wakka.php?wakka=")]
        public string Help1 {
            get {
                return ((string)(this["Help1"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sourceforge.net/projects/lsleditor/forums")]
        public string ForumLSLEditor {
            get {
                return ((string)(this["ForumLSLEditor"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://metaversegames.net/questions/lsl")]
        public string qasite {
            get {
                return ((string)(this["qasite"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string svnloc {
            get {
                return ((string)(this["svnloc"]));
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VersionControl {
            get {
                return ((bool)(this["VersionControl"]));
            }
            set {
                this["VersionControl"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VersionControlSVN {
            get {
                return ((bool)(this["VersionControlSVN"]));
            }
            set {
                this["VersionControlSVN"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UTF-8 (Notecard only)")]
        public string OutputFormat {
            get {
                return ((string)(this["OutputFormat"]));
            }
            set {
                this["OutputFormat"] = value;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://lsleditor.sourceforge.net/check4update.php")]
        public string Update {
            get {
                return ((string)(this["Update"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://lsleditor.sourceforge.net/update.php")]
        public string UpdateManifest {
            get {
                return ((string)(this["UpdateManifest"]));
            }
        }
    }
}
